# 1- Fondamentaux du Python

## a) Dictionnaires et tuples

### Créez un tuple qui associe votre login à votre âge

In [4]:
tup = ("fventuri", 154)

### Initialisez un dictionnaire à deux entrées qui associe le login de chacun de vos voisins à leur âge

In [3]:
dict = {"login1": 42, "login2": 24}

### Récupérez l'âge de l'un d'entre eux à partir du dictionnaire

In [5]:
dict["login1"]

42

### Ajoutez une entrée avec votre propre login

In [8]:
dict[tup[0]] = tup[1]

## b) Manipulation de listes

### Créez une liste A contenant les entiers suivants: 1, 3, 2, 7, 4, 10, 46

In [9]:
A = [1, 3, 2, 7, 4, 10, 46]


### Affichez les 3 premiers éléments de la liste A - en une ligne de code

In [10]:
A[:3]

[1, 3, 2]

### Créez une liste B qui contient seulement les 3e, 4e et 5e éléments de A . Votre ligne de code ne devrait contenir que 8 caractères (sans compter les espaces) - Vérifiez bien votre résultat!

In [11]:
B = A[3:6]

### Concaténez les listes A et B pour former la liste C

In [13]:
C

[1, 3, 2, 7, 4, 10, 46, 7, 4, 10]

### Ajoutez le nombre 5 à la liste A

In [16]:
A

[1, 3, 2, 7, 4, 10, 46, 5]

### Ajoutez un élément nul à la liste C

In [20]:
C

[1, 3, 2, 7, 4, 10, 46, 7, 4, 10, None]

## b) Fonctions

### Écrivez une fonction qui prend comme arguments une liste 'lst' et un entier 'n' et retourne le résultat de n concaténations de 'lst' avec elle-même (ex: lst=[1,2,3], n=2 --> [1,2,3,1,2,3])

In [25]:
def ft(lst, n):
    ret = []
    for i in range(n):
        ret += lst
    return ret

### Vous voulez rendre le paramètre 'n' optionnel et fixer sa valeur à 2 par défaut. Comment faites-vous?

In [27]:
def ft(lst, n=2):
    ret = []
    for i in range(n):
        ret += lst
    return ret

## c) Boucles

### Avec une boucle 'while', imprimez chaque élément de la liste C jusqu'à l'élément nul

In [30]:
i = 0
while (C[i] is not None):
    print(C[i])
    i += 1

1
3
2
7
4
10
46
7
4
10


### Calculez, avec une boucle 'for', le nombre d'entiers pairs présents dans la liste A

In [32]:
count = 0
for n in A:
    count += 1 if n % 2 == 0 else 0
print(count)

4


### Réécrivez l'expression suivante avec une boucle 'for' sur plusieurs lignes

In [ ]:
C = [element for element in A if element %2 == 0]

In [33]:
C = []
for element in A:
    if (element % 2 == 0):
        C.append(element)
print(C)

[2, 4, 10, 46]


# 2- Opérations sur matrices avec numpy

### Transformer les listes A et B en tableaux numpy a et b

In [2]:
import numpy
A = numpy.array(A)
B = numpy.array(B)

NameError: name 'A' is not defined

### Concaténez-les pour former un tableau c (a, b --> c)

In [40]:
C = numpy.concatenate((A, B))

### Divisez tous les éléments de c par 3 (sans utiliser de boucle)

In [43]:
C * 1/3

array([ 0.33333333,  1.        ,  0.66666667,  2.33333333,  1.33333333,
        3.33333333, 15.33333333,  1.66666667,  2.33333333,  1.33333333,
        3.33333333])

### Calculez la somme de tous les éléments de c (sans utiliser de boucle)

In [44]:
numpy.sum(C)

99

### Exécutez les trois cellules suivantes pour visualiser les matrices M et N

In [46]:
M = numpy.random.randint(10, size=(4,4))
N = numpy.random.randint(10, size=(4,4))

In [47]:
M

array([[4, 4, 8, 7],
       [7, 0, 7, 1],
       [6, 2, 7, 5],
       [6, 7, 5, 7]])

In [48]:
N

array([[4, 7, 6, 8],
       [2, 8, 1, 7],
       [9, 6, 7, 1],
       [6, 6, 2, 7]])

### Aditionnez les deux matrices

In [49]:
M + N

array([[ 8, 11, 14, 15],
       [ 9,  8,  8,  8],
       [15,  8, 14,  6],
       [12, 13,  7, 14]])

### Calculez le produit matriciel de M et N. Vérifiez votre opération en calculant les premières cellules à la main

In [52]:
numpy.dot(M, N)

array([[138, 150,  98, 117],
       [ 97,  97,  93,  70],
       [121, 130,  97, 104],
       [125, 170,  92, 151]])

### ** Bonus: Écrivez vous-mêmes une fonction de produit matriciel, avec des boucles imbriquées 

In [5]:
def mat_prod(mat1, mat2):
    m, n = mat1.shape
    n, o = mat2.shape
    ret = numpy.zeros((m, o))
    for i in range(m):
        for j in range(o):
            total = 0
            for k in range(n):
                total += mat1[i, k] * mat2[k, j]
            ret[i, j] = total
    return ret


### ** Comparez son temps de calcul à la fonction de numpy avec de très grosses matrices en entrée

In [6]:
import numpy
M1 = numpy.random.randint(10, size=(60,40))
N1 = numpy.random.randint(10, size=(60,40))
%time mat_prod(M1, N1)
%time numpy.dot(M1, N1)

IndexError: index 40 is out of bounds for axis 1 with size 40

ValueError: shapes (60,40) and (60,40) not aligned: 40 (dim 1) != 60 (dim 0)